config/routes.rb
Rails.application.routes.draw do
  root 'bills#index'
  resources :bills do
    resources :list_items
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  after_create_commit -> { broadcast_prepend_to "quotes" }
  after_update_commit -> { broadcast_replace_to "quotes" }
  after_destroy_commit -> { broadcast_remove_to "quotes" }

  has_many :list_items, dependent: :destroy
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :bill

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :amount, presence: true, numericality: { greater_than: 0 }

  scope :recent, -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all.order(created_at: :desc)
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.turbo_stream { flash.now[:notice] = "Bill was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.turbo_stream { flash.now[:notice] = "Bill was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Bill was successfully destroyed." }
    end
  end

  private

  def set_bill
    @bill = Bill.find(params[:id])
  end

  def bill_params
    params.require(:bill).permit(:title)
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_bill
  before_action :set_list_item, only: %i[ show edit update destroy ]

  # GET /list_items or /list_items.json
  def index
    @list_items = @bill.list_items.recent
  end

  # GET /list_items/1 or /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = @bill.list_items.build
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items or /list_items.json
  def create
    @list_item = @bill.list_items.build(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.turbo_stream { flash.now[:notice] = "List item was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1 or /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.turbo_stream { flash.now[:notice] = "List item was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1 or /list_items/1.json
  def destroy
    @list_item.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Bill was successfully destroyed." }
    end
  end

  private

  def set_bill
    @bill = Bill.find(params[:bill_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_list_item
    @list_item = ListItem.where(id: params[:id], bill_id: params[:bill_id]).first
  end

  # Only allow a list of trusted parameters through.
  def list_item_params
    params.require(:list_item).permit(:bill_id, :quantity, :amount, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill.html.erb
<li class="py-5 border-t-2 border-slate-300" id=<%= dom_id(bill) %>>
  <%= turbo_frame_tag dom_id(bill) do %>
    <div class="flex items-center space-x-4 bg-white py-6 shadow-slate-200">
      <div class="flex-1 min-w-0">
        <p class="text-2xl font-medium text-gray-900 truncate dark:text-white">
            <%= bill.title %> 
        </p>
      </div>
      <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white justify-evenly">
        <%= link_to "Edit Bill", edit_bill_path(bill), class: "text-sm font-medium text-white hover:text-slate-950 dark:text-white p-2 rounded-lg bg-green-400 mr-2"%>
        <%= button_to "Delete Bill", bill, method: :delete, class: "text-sm font-medium text-white hover:text-slate-950 dark:text-white p-2 rounded-lg bg-red-400"%>
      </div>
    </div> 
  <% end %>

  <div class="py-2">
    <%= render 'bills/list_items/list', bill: bill%>
  </div>
</li>

app/views/bills/_form.html.erb
<div class="flex items-center flex-shrink-0 w-full mx-auto sm:w-auto mb-5">
    <%= form_with(model: bill, class: "flex flex-col items-center w-full md:flex-row") do |form| %>
      <%= form.text_field :title, class: 'w-full text-gray-700 border rounded py-3 px-4 mr-3 leading-tight focus:outline-none focus:bg-white', id: 'bill', placeholder: 'Title' %>
      <%= form.submit btn_name, class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full mr-2 sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>
      <%= link_to "Cancel", bills_path, class: 'bg-slate-100 hover:bg-slate-200 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
    <% end %>
</div>

app/views/bills/_header.html.erb
<%= turbo_frame_tag dom_id(Bill.new) do %>
  <div class="flex items-center justify-between mb-4">
    <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Bills</h5>
    <%= link_to "New bill", new_bill_path, class: "text-sm font-medium text-white hover:text-slate-950 dark:text-white p-2 rounded-lg bg-blue-400"%>
  </div>
<% end %>

app/views/bills/create.turbo_stream.erb
<%= turbo_stream.prepend 'bills', partial: 'bills/bill', locals: { bill: @bill } %>
<%= turbo_stream.update dom_id(Bill.new), partial: 'bills/header' %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/bills/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@bill) %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/bills/edit.html.erb
<h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Edit Bill with tile: <%= @bill.title%></h5>

<%= turbo_frame_tag dom_id(@bill) do %>
  <%= render "form", bill: @bill, btn_name: 'Update' %>
<% end %>

app/views/bills/index.html.erb
<h1 class="container mx-auto w-full text-5xl font-bold text-center my-4">Turbo Hotwire with Rails + Tailwindcss</h1>
<div class="container mx-auto w-full p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
  <%= render "bills/header" %>  
  <%= turbo_stream_from "quotes" %> 
  <div class="flow-root">
      <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
        <%= turbo_frame_tag 'bills' do %>
          <%= render @bills %> 
        <% end %>
      </ul>
  </div>
</div>

app/views/bills/list_items/_list.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <div class="flex justify-between items-center w-full bg-gray-300 px-4">
    <div class="p-auto text-xl w-40">Title</div>
    <div class="p-auto text-xl w-40">Quantity</div>
    <div class="p-auto text-xl w-40">Amount</div>
    <div class="p-auto text-xl w-40">Action</div>
  </div>

  <%= turbo_frame_tag 'list_item' do %>
    <%- bill.list_items.recent.each do |item| %>
      <%= render "list_items/list_item", list_item: item %>
    <% end %>
  <% end %>

  <%= render "bills/list_items/new", bill: bill %>
</div>

app/views/bills/list_items/_new.html.erb
<%= turbo_frame_tag 'list_item_new' do %>
  <div class="flex justify-center items-center w-40 py-4 mx-auto">
    <%= link_to 'Add new item', new_bill_list_item_path(bill_id: bill.id), class: "bg-blue-600 p-2 rounded-md text-white" %>
  </div>
<% end %>

app/views/bills/new.html.erb
<h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">New Bills</h5>

<%= turbo_frame_tag "new_bill" do %>
  <%= render "form", bill: @bill, btn_name: 'Create' %>
<% end %>

app/views/bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bill %>

<div>
  <%= link_to "Edit this bill", edit_bill_path(@bill) %> |
  <%= link_to "Back to bills", bills_path %>

  <%= button_to "Destroy this bill", @bill, method: :delete %>
</div>

app/views/bills/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@bill), partial: 'bills/bill', locals: { bill: @bill } %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="<%= class_names('flex rounded-lg h-10', 'bg-emerald-300': flash_type == 'notice')%>"
       data-controller="removals"
  >
    <p class="text-2xl font-bold text-slate-50 text-center m-auto">
      <%= message %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTailwind</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100&family=Poppins:wght@300;400;500;700&display=swap" rel="stylesheet">

  </head>

  <body>
    <main class="container mx-auto">
      <div id="flash" class="flash">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/list_items/_form.html.erb
<%= form_for [@bill, @list_item], html: { class: 'py-5 px-2' } do |f| %>
  <div class="flex justify-between items-center w-full bg-white border-b dark:bg-gray-900 dark:border-gray-700 p-4">
    <div class="p-auto text-left text-md w-40">
      <%= f.text_field :name, require: true, placeholder: 'Title item', class: 'border border-1 p-2 text-gray-400 focus:text-black rounded-md' %>
    </div>
    <div class="p-auto text-left text-md w-40">
      <%= f.number_field :quantity, require: true, placeholder: 'Quantity item', class: 'border border-1 p-2 text-gray-400 focus:text-black rounded-md' %>
    </div>
    <div class="p-auto text-left text-md w-40">
      <%= f.number_field :amount, require: true, placeholder: 'Unit price item', class: 'border border-1 p-2 text-gray-400 focus:text-black rounded-md' %>
    </div>
    <div class="p-auto text-md text-left flex w-40">
      <%= f.submit button_title, data: { disable_with: false }, class: 'cursor-pointer border border-1 bg-blue-700 p-2 text-white rounded-md' %>
      <%= link_to "Cancel", bills_path, class: 'bg-slate-100 hover:bg-slate-200 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center' %>
    </div>
  </div>
<% end %>

app/views/list_items/_list_item.html.erb
<%= turbo_frame_tag dom_id(list_item) do %>
  <div class="flex justify-between items-center w-full bg-white border-b dark:bg-gray-900 dark:border-gray-700 p-4">
    <div class="p-auto text-left text-md w-40"><%= list_item.name %></div>
    <div class="p-auto text-left text-md w-40"><%= list_item.quantity %></div>
    <div class="p-auto text-left text-md w-40"><%= list_item.amount %></div>
    <div class="p-auto text-md text-left flex w-40">
      <%= link_to "Edit", edit_bill_list_item_path(list_item.bill_id, list_item.id), class: "text-sm font-medium text-white hover:text-slate-950 dark:text-white p-2 rounded-lg bg-green-400 mr-2"%>
      <%= button_to "Delete", bill_list_item_path(list_item.bill_id, list_item.id), method: :delete, class: "text-sm font-medium text-white hover:text-slate-950 dark:text-white p-2 rounded-lg bg-red-400"%>
    </div>
  </div>
<% end %>

app/views/list_items/create.turbo_stream.erb
<%= turbo_stream.prepend 'list_item', partial: 'list_items/list_item', locals: { list_item: @list_item } %>
<%= turbo_stream.update 'list_item_new', partial: 'bills/list_items/new', locals: {bill: @bill} %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/list_items/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@list_item) %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/list_items/edit.html.erb
<%= turbo_frame_tag dom_id(@list_item) do %>
  <%= render "form", button_title: 'Edit item'%>
<% end %>

app/views/list_items/new.html.erb
<h1>New list item</h1>

<%= turbo_frame_tag "list_item_new" do %>
  <%= render "form", button_title: 'Add item' %>
<% end %>

app/views/list_items/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="table-auto">
  <thead>
    <tr>
      <th>Title</th>
      <th>Quanity</th>
      <th>Unit price</th>
    </tr>
  </thead>
  <tbody>
    
  </tbody>
</table>


<%= render @list_item %>

<div>
  <%= link_to "Edit this list item", edit_list_item_path(@list_item) %> |
  <%= link_to "Back to list items", list_items_path %>

  <%= button_to "Destroy this list item", @list_item, method: :delete %>
</div>

app/views/list_items/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@list_item), partial: 'list_items/list_item', locals: { list_item: @list_item } %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>